M48
; DRILL file {KiCad (6.0.6)} date Thu Jun 23 13:21:27 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-23T13:21:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X18.39Y-11.43
X18.39Y-13.97
X18.39Y-16.51
T2
X8.89Y-2.54
X8.89Y-6.35
X8.89Y-21.59
X8.93Y-25.4
X13.89Y-2.54
X13.93Y-25.4
X13.97Y-6.35
X13.97Y-21.59
T3
X3.81Y-11.43
X3.81Y-13.97
X3.81Y-16.51
T0
M30
